runtime: nodejs16
handlers:
  - url: /(.*\..+)$
    http_headers: 
      Access-Control-Allow-Origin: https://assignemtn1-gae-react.uk.r.appspot.com
    static_files: build/\1
    upload: build/(.*\..+)$
  - url: /.*
    http_headers: 
      Access-Control-Allow-Origin: https://assignemtn1-gae-react.uk.r.appspot.com
    static_files: build/index.html
    upload: build/index.html